package com.comtop.app.db;

import java.util.Map;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personalCertificateInfDaoConfig;
    private final DaoConfig personalCertificateDaoConfig;
    private final DaoConfig holderEmployeeProjectDaoConfig;
    private final DaoConfig holderEmployeeItemDaoConfig;

    private final PersonalCertificateInfDao personalCertificateInfDao;
    private final PersonalCertificateDao personalCertificateDao;
    private final HolderEmployeeProjectDao holderEmployeeProjectDao;
    private final HolderEmployeeItemDao holderEmployeeItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personalCertificateInfDaoConfig = daoConfigMap.get(PersonalCertificateInfDao.class).clone();
        personalCertificateInfDaoConfig.initIdentityScope(type);

        personalCertificateDaoConfig = daoConfigMap.get(PersonalCertificateDao.class).clone();
        personalCertificateDaoConfig.initIdentityScope(type);

        holderEmployeeProjectDaoConfig = daoConfigMap.get(HolderEmployeeProjectDao.class).clone();
        holderEmployeeProjectDaoConfig.initIdentityScope(type);

        holderEmployeeItemDaoConfig = daoConfigMap.get(HolderEmployeeItemDao.class).clone();
        holderEmployeeItemDaoConfig.initIdentityScope(type);

        personalCertificateInfDao = new PersonalCertificateInfDao(personalCertificateInfDaoConfig, this);
        personalCertificateDao = new PersonalCertificateDao(personalCertificateDaoConfig, this);
        holderEmployeeProjectDao = new HolderEmployeeProjectDao(holderEmployeeProjectDaoConfig, this);
        holderEmployeeItemDao = new HolderEmployeeItemDao(holderEmployeeItemDaoConfig, this);

        registerDao(PersonalCertificateInf.class, personalCertificateInfDao);
        registerDao(PersonalCertificate.class, personalCertificateDao);
        registerDao(HolderEmployeeProject.class, holderEmployeeProjectDao);
        registerDao(HolderEmployeeItem.class, holderEmployeeItemDao);
    }
    
    public void clear() {
        personalCertificateInfDaoConfig.getIdentityScope().clear();
        personalCertificateDaoConfig.getIdentityScope().clear();
        holderEmployeeProjectDaoConfig.getIdentityScope().clear();
        holderEmployeeItemDaoConfig.getIdentityScope().clear();
    }

    public PersonalCertificateInfDao getPersonalCertificateInfDao() {
        return personalCertificateInfDao;
    }

    public PersonalCertificateDao getPersonalCertificateDao() {
        return personalCertificateDao;
    }

    public HolderEmployeeProjectDao getHolderEmployeeProjectDao() {
        return holderEmployeeProjectDao;
    }

    public HolderEmployeeItemDao getHolderEmployeeItemDao() {
        return holderEmployeeItemDao;
    }

}
