package com.comtop.app.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table HOLDER_EMPLOYEE_PROJECT.
 */
public class HolderEmployeeProject {

    private Long id;
    private String holderEmployeeId;
    private String projectId;
    private String projectName;
    private Integer projectType;

    public HolderEmployeeProject() {
    }

    public HolderEmployeeProject(Long id) {
        this.id = id;
    }

    public HolderEmployeeProject(Long id, String holderEmployeeId, String projectId, String projectName, Integer projectType) {
        this.id = id;
        this.holderEmployeeId = holderEmployeeId;
        this.projectId = projectId;
        this.projectName = projectName;
        this.projectType = projectType;
    }
    
    public HolderEmployeeProject( String holderEmployeeId, String projectId, String projectName, Integer projectType) {
        this.holderEmployeeId = holderEmployeeId;
        this.projectId = projectId;
        this.projectName = projectName;
        this.projectType = projectType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getHolderEmployeeId() {
        return holderEmployeeId;
    }

    public void setHolderEmployeeId(String holderEmployeeId) {
        this.holderEmployeeId = holderEmployeeId;
    }

    public String getProjectId() {
        return projectId;
    }

    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    public String getProjectName() {
        return projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public Integer getProjectType() {
        return projectType;
    }

    public void setProjectType(Integer projectType) {
        this.projectType = projectType;
    }

}
