package com.comtop.app.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PERSONAL_CERTIFICATE_INF.
 */
public class PersonalCertificateInf {

    private Long id;
    private String holderCertificateId;
    private String idCardNo;
    private String userName;
    private String contractorName;
    private Integer sex;
    private Integer blacked;
    private java.util.Date blackedDate;
    private String blackedRemark;

    public PersonalCertificateInf() {
    }

    public PersonalCertificateInf(Long id) {
        this.id = id;
    }

    public PersonalCertificateInf(Long id, String holderCertificateId, String idCardNo, String userName, String contractorName, Integer sex, Integer blacked, java.util.Date blackedDate, String blackedRemark) {
        this.id = id;
        this.holderCertificateId = holderCertificateId;
        this.idCardNo = idCardNo;
        this.userName = userName;
        this.contractorName = contractorName;
        this.sex = sex;
        this.blacked = blacked;
        this.blackedDate = blackedDate;
        this.blackedRemark = blackedRemark;
    }
    
    public PersonalCertificateInf(String holderCertificateId, String idCardNo, String userName, String contractorName, Integer sex, Integer blacked, java.util.Date blackedDate, String blackedRemark) {
        this.holderCertificateId = holderCertificateId;
        this.idCardNo = idCardNo;
        this.userName = userName;
        this.contractorName = contractorName;
        this.sex = sex;
        this.blacked = blacked;
        this.blackedDate = blackedDate;
        this.blackedRemark = blackedRemark;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getHolderCertificateId() {
        return holderCertificateId;
    }

    public void setHolderCertificateId(String holderCertificateId) {
        this.holderCertificateId = holderCertificateId;
    }

    public String getIdCardNo() {
        return idCardNo;
    }

    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getContractorName() {
        return contractorName;
    }

    public void setContractorName(String contractorName) {
        this.contractorName = contractorName;
    }

    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public Integer getBlacked() {
        return blacked;
    }

    public void setBlacked(Integer blacked) {
        this.blacked = blacked;
    }

    public java.util.Date getBlackedDate() {
        return blackedDate;
    }

    public void setBlackedDate(java.util.Date blackedDate) {
        this.blackedDate = blackedDate;
    }

    public String getBlackedRemark() {
        return blackedRemark;
    }

    public void setBlackedRemark(String blackedRemark) {
        this.blackedRemark = blackedRemark;
    }

}
